#!/bin/sh
# Builds/updates a single table-of-contents page linking to everything deploy-standalone.sh,
# deploy-embedded.sh, deploy-posts.sh, and deploy-pages.sh just deployed. Must run last.
set -e
cd "$(dirname "$0")"
. ./lib/config.sh
. ./lib/safety-check.sh

# tail -n1 / grep filters below defend against stray warning lines (e.g. a PHP extension
# mismatch) that some environments print to stdout ahead of wp-cli's actual output.
SITE_URL=$(wp option get siteurl | tail -n1)
STATIC_DEST="$WP_PATH/static-documents/test-corpus"

file_list_html() {
  # $1 = subfolder name under STATIC_DEST, $2 = heading
  sub="$1"
  heading="$2"
  dirpath="$STATIC_DEST/$sub"
  [ -d "$dirpath" ] || return 0
  echo "<h3>$heading</h3><ul>"
  for f in "$dirpath"/*; do
    [ -f "$f" ] || continue
    name=$(basename "$f")
    echo "<li><a href=\"$SITE_URL/static/test-corpus/$sub/$name\">$name</a></li>"
  done
  echo "</ul>"
}

embedded_list_html() {
  # $1 = subfolder name under EMBEDDED_DEPLOY_PATH/test-corpus, $2 = heading
  sub="$1"
  heading="$2"
  if [ -z "$EMBEDDED_DEPLOY_PATH" ]; then
    return 0
  fi
  dirpath="$EMBEDDED_DEPLOY_PATH/test-corpus/$sub"
  [ -d "$dirpath" ] || return 0
  echo "<h3>$heading</h3><ul>"
  for f in "$dirpath"/*; do
    [ -f "$f" ] || continue
    name=$(basename "$f")
    echo "<li><a href=\"$EMBEDDED_BASE_URL/test-corpus/$sub/$name\">$name</a></li>"
  done
  echo "</ul>"
}

content_list_html() {
  # $1 = toc_group value, $2 = heading. Covers both posts/hostile-posts (post_type=post)
  # and pages/hostile-pages (post_type=page) — excludes the ToC page itself, which never
  # gets a _test_corpus_toc_group value.
  group="$1"
  heading="$2"
  echo "<h3>$heading</h3><ul>"
  for id in $(wp post list --meta_key=_test_corpus_slug --post_type=any --post_status=any --field=ID | grep -E '^[0-9]+$'); do
    tg=$(wp post meta get "$id" _test_corpus_toc_group 2>/dev/null | tail -n1)
    if [ "$tg" = "$group" ]; then
      url=$(wp post list --post__in="$id" --post_type=any --post_status=any --field=url | tail -n1)
      title=$(wp post list --post__in="$id" --post_type=any --post_status=any --field=post_title | tail -n1)
      post_type=$(wp post list --post__in="$id" --post_type=any --post_status=any --field=post_type | tail -n1)
      echo "<li><a href=\"$url\">$title</a> ($post_type)</li>"
    fi
  done
  echo "</ul>"
}

content=$(cat <<HTML
<p>Generated by test-corpus/scripts/generate-toc.sh — re-run deploy-all.sh to refresh.</p>

<h2>Standalone documents</h2>
$(file_list_html standalone "Standalone")
$(file_list_html hostile-standalone "Hostile standalone")

<h2>Embedded HDOC pages</h2>
$(embedded_list_html embedded "Embedded")
$(embedded_list_html hostile-embedded "Hostile embedded")

<h2>Posts &amp; pages</h2>
$(content_list_html starter "Starter")
$(content_list_html full "Full")
$(content_list_html hostile "Hostile")
HTML
)

existing_id=$(wp post list --meta_key=_test_corpus_slug --meta_value=test-corpus-toc \
  --post_type=page --post_status=any --field=ID | grep -E '^[0-9]+$' | head -n1)

if [ -n "$existing_id" ]; then
  toc_id="$existing_id"
  wp post update "$toc_id" --post_title="[test-corpus] Table of contents" \
    --post_content="$content" --post_type=page --post_status=publish >/dev/null
else
  toc_id=$(wp post create --post_title="[test-corpus] Table of contents" \
    --post_content="$content" --post_type=page --post_status=publish --porcelain | tail -n1)
  wp post meta update "$toc_id" _test_corpus_slug test-corpus-toc >/dev/null
fi

wp post meta update "$toc_id" _hdoc_display_mode none >/dev/null

toc_url=$(wp post list --post__in="$toc_id" --post_type=page --post_status=any --field=url | tail -n1)
echo "ToC: $toc_url"
